export const AUTH_LOADER_MESSAGES = {
  LOADING_AUTHENTICATION: "Loading authentication...",
  CHECKING_SESSION: "Checking session...",
} as const;

export const AUTH_DEFAULT_MESSAGES = {
  API_REQUEST_FAILED: "Something went wrong while calling API",
  LOGIN_SUCCESS: "Login successful",
  LOGIN_FAILED: "Login failed",
  REGISTRATION_SUCCESS: "Registration successful",
  REGISTRATION_FAILED: "Registration failed",
  OTP_SENT_SUCCESS: "OTP sent successfully",
  OTP_RESENT_SUCCESS: "OTP resent successfully",
  SEND_OTP_FAILED: "Unable to send OTP",
  RESEND_OTP_FAILED: "Unable to resend OTP",
  EMAIL_VERIFIED_SUCCESS: "Email verified successfully",
  EMAIL_VERIFICATION_FAILED: "Email verification failed",
  EMAIL_NOT_FOUND: "Email not found. Please register again.",
} as const;

export const AUTH_UI_TEXT = {
  LOADING_PAGE: "Loading page...",
  LOGIN_TITLE: "Login",
  LOGIN_SUBTITLE: "Login to continue",
  REGISTER_TITLE: "Register",
  REGISTER_SUBTITLE: "Register and continue to email verification",
  VERIFY_EMAIL_TITLE: "Verify your email",
  VERIFY_EMAIL_SUBTITLE: "The verification code has been sent to your email",
  LOGIN_BUTTON: "Login",
  LOGGING_IN_BUTTON: "Logging in",
  REGISTER_BUTTON: "Register",
  REGISTERING_BUTTON: "Registering",
  VERIFY_EMAIL_BUTTON: "Verify Email",
  VERIFYING_BUTTON: "Verifying",
  RESEND_OTP_BUTTON: "Resend OTP",
  SENDING_BUTTON: "Sending...",
  VERIFY_EMAIL_PENDING_TITLE: "Email verification pending",
  VERIFY_EMAIL_PENDING_MESSAGE: "Please verify your email with OTP before login.",
  VERIFY_EMAIL_PENDING_PRIMARY_LABEL: "Verify Email",
  APPROVAL_PENDING_TITLE: "Account approval pending",
  APPROVAL_PENDING_MESSAGE: "Your account is waiting for approval. Please try again after approval.",
  CANCEL_BUTTON: "Cancel",
  LOGIN_SWITCH_TEXT: "Don't have an account?",
  LOGIN_SWITCH_LINK: "Register",
  REGISTER_SWITCH_TEXT: "Already have an account?",
  REGISTER_SWITCH_LINK: "Login",
  VERIFY_EMAIL_BACK_TEXT: "Register",
  VERIFY_EMAIL_HELPER_FALLBACK: "Email not provided",
} as const;

export const AUTH_FORM_TEXT = {
  EMAIL_LABEL: "Email",
  EMAIL_PLACEHOLDER: "example@gmail.com",
  PASSWORD_LABEL: "Password",
  PASSWORD_PLACEHOLDER: "Example@123",
  PASSWORD_INFO: "Use at least 8 characters with uppercase, lowercase, and number.",
  ROLE_LABEL: "Role",
  NAME_LABEL: "Name",
  NAME_PLACEHOLDER: "Rahul Chouhan",
  OTP_LABEL: "OTP",
  OTP_PLACEHOLDER: "Enter 6 digit OTP",
  ROLE_OPTIONS: {
    HR: "HR",
    CANDIDATE: "Candidate",
    INTERVIEWER: "Interviewer",
  },
} as const;

export const AUTH_VALIDATION_MESSAGES = {
  ROLE_REQUIRED: "Role is required",
  NAME_REQUIRED: "Name is required",
  NAME_INVALID: "Please enter full name like Rahul Chouhan",
  NAME_ONLY_LETTERS: "Only letters and spaces are allowed",
  EMAIL_REQUIRED: "Email is required",
  EMAIL_INVALID: "Please enter valid email like example@gmail.com",
  EMAIL_NO_SPACES: "Email cannot contain spaces",
  PASSWORD_REQUIRED: "Password is required",
  PASSWORD_NO_SPACES: "Password cannot contain spaces",
  PASSWORD_TOO_SHORT: "Password must be at least 8 characters",
  PASSWORD_INVALID: "Use password like Example@123 (upper, lower, number, min 8)",
  PASSWORD_TOO_LONG: "Password is too long",
  OTP_ONLY_DIGITS: "Only digits are allowed",
  OTP_INVALID_LENGTH: "OTP must be 6 digits",
} as const;
