export const APPLICATION_CONSTANTS = {
  HTTP_STATUS_CODES: {
    OK: 200,
    CREATED: 201,
    BAD_REQUEST: 400,
    INTERNAL_SERVER_ERROR: 500,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    CONFLICT: 409,
    UNAUTHORIZED: 401,
    TOO_MANY_REQUESTS: 429,
  },
  GOOGLE_OAUTH: {
    AUTH_SCOPES: ['openid', 'email', 'profile'] as const,
    CALENDAR_SCOPE: 'https://www.googleapis.com/auth/calendar',
    ACCESS_TYPE_OFFLINE: 'offline',
    ACCESS_TYPE_ONLINE: 'online',
    PROMPT_CONSENT: 'consent',
    PROMPT_SELECT_ACCOUNT: 'select_account',
    INVALID_GRANT_ERROR: 'invalid_grant',
    STATE_BYTE_LENGTH: 16,
    STATE_COOKIE_NAME: 'googleOAuthState',
    CONTEXT_COOKIE_NAME: 'googleOAuthContext',
    STATE_MAX_AGE_MS: 10 * 60 * 1000,
    TIMEZONE: 'Asia/Kolkata',
    CONFERENCE_SOLUTION_TYPE: 'hangoutsMeet',
    REQUEST_ID_PREFIX: 'interview-',
  },
  CLOUDINARY: {
    RESOURCE_TYPES: ['raw', 'image'] as const,
    RAW_UPLOAD_PATH: '/raw/upload/',
    RESULT_NOT_FOUND: 'not found',
    RESUME_FOLDER: 'resumes',
    RESOURCE_TYPE_AUTO: 'auto',
    ERROR_CODES: {
      NOT_FOUND: 404,
    },
  },
  SOCKET_EVENTS: {
    CHAT_MESSAGE: 'chat:message',
    CHAT_TYPING: 'chat:typing',
    CHAT_SEEN: 'chat:seen',
    CONVERSATION_UPDATED: 'chat:conversation_updated',
    CONVERSATION_CREATED: 'chat:conversation_created',
    NOTIFICATION: 'notification',
  },
  EMPTY_STRING: '',
  TOKEN_COOKIE_NAME: 'authToken',
  TOKEN_EXPIRES_IN: '7d',
  COOKIE_MAX_AGE_MS: 7 * 24 * 60 * 60 * 1000,
  OTP_EXPIRES_IN_MINUTES: 10,
  OTP_MAX_ATTEMPTS: 5,
  EMAIL: {
    DEFAULT_FROM_NAME: 'Recruitment Portal',
    DEFAULT_SMTP_PORT: 587,
    SECURE_SMTP_PORT: 465,
    ICS_DOMAIN: 'recruitment-application.local',
    ICS_FILENAME: 'interview-invite.ics',
  },
  INTERVIEW: {
    DEFAULT_DESCRIPTION: 'Candidate Interview',
    MEET_LINK_TEXT: 'Meet Link: ',
    SUMMARY_PREFIX: 'Interview - ',
    SLOT_INTERVAL_MINUTES: 30,
    WORKDAY_START_HOUR: 9,
    WORKDAY_END_HOUR: 18,
  },
  FEEDBACK_STATUSES: ['PENDING', 'NEEDS_REVIEW', 'REVIEWED'] as const,
  INTERVIEW_RESULTS: {
    PASSED: 'Passed',
    FAILED: 'Failed',
    PENDING: 'Pending',
  } as const,
  USER_ROLES: {
    HR: 'hr',
    CANDIDATE: 'candidate',
    INTERVIEWER: 'interviewer',
  } as const,
  PASSWORD_MIN_LENGTH: 8,
  RESUME_MAX_SIZE_BYTES: 5 * 1024 * 1024,
  RESUME_ALLOWED_MIME_TYPES: [
    'application/pdf',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  ] as const,
} as const;
