export const APPLICATION_CONSTANTS = {
  HTTP_STATUS_CODES: {
    BAD_REQUEST: 400,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    UNAUTHORIZED: 401,
  },
  TOKEN_COOKIE_NAME: "authToken",
  TOKEN_EXPIRES_IN: "7d",
  COOKIE_MAX_AGE_MS: 7 * 24 * 60 * 60 * 1000,
  OTP_EXPIRES_IN_MINUTES: 10,
  OTP_MAX_ATTEMPTS: 5,
  EMAIL_DEFAULT_FROM_NAME: "Recruitment Portal",
  EMAIL_DEFAULT_SMTP_PORT: 587,
  EMAIL_SECURE_SMTP_PORT: 465,
} as const;
