export const PROFILE_DEFAULT_MESSAGES = {
  LOADING_PROFILE: 'Loading profile...',
  PROFILE_LOAD_FAILED: 'Unable to load profile details.',
  PROFILE_UPDATED_SUCCESS: 'Profile updated successfully',
  PROFILE_UPDATE_FAILED: 'Failed to update profile',
  RESUME_UPLOAD_FAILED: 'Failed to upload resume. Please try again.',
} as const;

export const PROFILE_UI_TEXT = {
  COMPLETE_HR_PROFILE: 'Complete HR Profile',
  COMPLETE_INTERVIEWER_PROFILE: 'Complete Interviewer Profile',
  COMPLETE_CANDIDATE_PROFILE: 'Complete Candidate Profile',
  COMPLETE_PROFILE_DESCRIPTION:
    'Your profile is incomplete. Please complete your profile to apply for jobs. Required information includes phone number, resume, skills, experience, and location.',
  COMPLETE_REQUIRED_FIELDS: 'Please complete the required fields to continue.',
  PHONE: 'Phone',
  PHONE_NUMBER: 'Phone Number',
  PHONE_PLACEHOLDER: 'Enter your phone number',
  RESUME: 'Resume',
  RESUME_UPLOAD_INFO: 'Allowed formats: PDF, DOC, DOCX. Max size: 5MB.',
  OPEN_RESUME_ARIA: 'Open uploaded resume',
  RESUME_UPLOADED: 'Resume Uploaded',
  NO_RESUME: 'No resume uploaded yet',
  REPLACE_RESUME: 'Replace Resume',
  UPLOADING: 'Uploading...',
  UPLOAD_RESUME: 'Upload Resume',
  SKILLS: 'Skills',
  SKILLS_PLACEHOLDER: 'e.g. React, Node.js, Java',
  EXPERIENCE_YEARS: 'Experience Years',
  EXPERIENCE: 'Experience',
  EXPERIENCE_YEARS_PLACEHOLDER: 'Enter years of experience',
  CURRENT_LOCATION: 'Current Location',
  CURRENT_LOCATION_PLACEHOLDER: 'Enter your current location',
  POSITION: 'Position',
  POSITION_PLACEHOLDER_HR: 'e.g. Senior HR Executive',
  POSITION_PLACEHOLDER_INTERVIEWER: 'e.g. Senior Software Engineer',
  DESIGNATION: 'Designation',
  DESIGNATION_PLACEHOLDER: 'Enter your designation',
  EXPERIENCE_LEVEL: 'Experience Level',
  EXPERIENCE_LEVEL_PLACEHOLDER_HR: 'e.g. 3-5 years',
  EXPERIENCE_LEVEL_PLACEHOLDER_INTERVIEWER: 'e.g. 5+ years',
  EXPERIENCE_LEVEL_PLACEHOLDER: 'Enter experience level',
  DEPARTMENT: 'Department',
  DEPARTMENT_PLACEHOLDER: 'e.g. Talent Acquisition',
  DEPARTMENT_INPUT_PLACEHOLDER: 'Enter your department',
  TECH_STACK: 'Tech Stack',
  TECH_STACK_PLACEHOLDER: 'e.g. React, Node.js',
  TECH_STACK_INPUT_PLACEHOLDER: 'Enter tech stack',
  SAVE_PROFILE: 'Save Profile',
  SAVE_CHANGES: 'Save Changes',
  SAVING: 'Saving...',
  CANCEL: 'Cancel',
  PERSONAL_INFORMATION: 'Personal Information',
  PROFESSIONAL_INFORMATION: 'Professional Information',
  FULL_NAME: 'Full Name',
  FULL_NAME_PLACEHOLDER: 'Enter your full name',
  EMAIL: 'Email',
  EMAIL_PLACEHOLDER: 'Email address',
  ROLE_PREFIX: 'Role:',
  EMAIL_PREFIX: 'Email:',
  EDIT_PROFILE_ARIA: 'Edit profile',
  EDIT_PROFILE_TITLE: 'Edit Profile',
  RESUME_INFO_ARIA: 'Resume upload info',
  FIELD_ERROR_PLACEHOLDER: '\u00A0',
  ROLE_LABELS: {
    hr: 'HR',
    interviewer: 'Interviewer',
    candidate: 'Candidate',
  },
} as const;

export const PROFILE_VALIDATION_MESSAGES = {
  PHONE_REQUIRED: 'Phone is required.',
  PHONE_INVALID: 'Phone number must be 10 digits.',
  RESUME_REQUIRED: 'Resume is required.',
  SKILLS_REQUIRED: 'Skills field cannot be empty.',
  SKILLS_REQUIRED_PANEL: 'Skills are required',
  SKILLS_MAX_LENGTH: (count: number) => `Skills cannot exceed ${count} characters.`,
  EXPERIENCE_INVALID: 'Experience must be a valid number between 0 and 50.',
  EXPERIENCE_INVALID_PANEL: (count: number) =>
    `Experience must be a valid number between 0 and ${count}`,
  CURRENT_LOCATION_REQUIRED: 'Current location is required.',
  CURRENT_LOCATION_REQUIRED_PANEL: 'Current location is required',
  CURRENT_LOCATION_MAX_LENGTH: (count: number) => `Location cannot exceed ${count} characters.`,
  CURRENT_LOCATION_MAX_LENGTH_PANEL: (count: number) =>
    `Current location cannot exceed ${count} characters`,
  POSITION_REQUIRED: 'Position is required',
  DESIGNATION_REQUIRED: 'Designation is required',
  EXPERIENCE_LEVEL_REQUIRED: 'Experience level is required',
  DEPARTMENT_REQUIRED: 'Department is required',
  TECH_STACK_REQUIRED: 'Tech stack is required',
  FULL_NAME_REQUIRED: 'Full name is required',
  PHONE_NUMBER_REQUIRED: 'Phone number is required',
  PHONE_NUMBER_INVALID: 'Phone number must be 10 digits',
  RESUME_URL_REQUIRED: 'Resume URL is required',
} as const;
