export const CHAT_UI_LABELS = {
  EMPTY_TITLE: 'No Chats Yet',
  EMPTY_DESCRIPTION: 'No conversations available right now.',
  START_CHAT: 'Start Chat With HR',
  STARTING_CHAT: 'Starting...',
  PANEL_TITLE: 'Chat',
  HEADER_MORE: 'More',
  HEADER_SEARCH: 'Search',
  HEADER_NEW_CHAT: 'New chat',
  FILTER_UNREAD: 'Unread',
  FILTER_CHANNELS: 'Channels',
  FILTER_CHATS: 'Chats',
  DEFAULT_TITLE: 'Conversation',
  DEFAULT_LAST_MESSAGE: 'Start the conversation...',
  ONLINE: 'Online',
  OFFLINE: 'Offline',
  COMPOSER_PLACEHOLDER: 'Type a message',
  SEND: 'Send',
  LOADING_CHATS: 'Loading chats...',
  LOADING_MESSAGES: 'Loading messages...',
  CHAT_LOAD_ERROR: 'Unable to load chats right now.',
  MESSAGE_LOAD_ERROR: 'Unable to load messages right now.',
  RETRY: 'Retry',
  SEND_RETRY: 'Try again',
} as const;
